# 数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456



  # 设置全局日期格式,如果设置这个格式,则代码中@DateTimeFormat(pattern = "dd/MM/yyyy") 无效!!
  mvc:
    format:
      date: yyyy-MM-dd
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8



# Mybatis 配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

logging:
  level:
    com.wxwl.hotelsystem.mapper: debug

  # redis配置
  # 基本连接信息配置
spring.redis.database: 0
spring.redis.host: localhost
spring.redis.port: 6379

  # 连接池信息配置
spring.redis.jedis.pool.max-active: 8
spring.redis.jedis.pool.max-idle: 8
spring.redis.jedis.pool.max-wait: 10ms
spring.redis.jedis.pool.min-idle: 0
  # 定义spring缓存类型
spring.cache.type: REDIS
 # 定义缓存空间
spring.cache.cache-names: cache



